---
title: "Exercise 10: Classification models, part 2"
subtitle: "Data Projects & Hackathon 2"
output: html_notebook
---

In today's exercise we will work on the dataset `Meteo_daily.csv` and we will try different models to predict if we have a serene day in `SMA` during summer. 

Recall that a serene day means that the average cloud coverage of the day is less than $20\%$. This is encoded in the variable `cloudLess20` in the dataset which is 1 if the day was serene and 0 if it was not.  

We want to predict `cloudLess20` from the other variables. Here we will always use a simplified model that uses as predictors only the variables `sunshine, windGust, tempMean, precTot, humidMean`.


## **1.** Naive Bayes


1. Create a train/test split for a dataset with those variables with the function `initial_split` from the package `rsample`.
  * Understand what the option `strata` does. 
  * What happens if you do not put `strata=cloudLess20`? 
    
2. Fit a Naive Bayes model that predicts `cloudLess20` from the predictors. 

3. Compute the accuracy of the model on the test data. Is it a good accuracy? Are we doing better than a dummy model that always predicts the most frequent class?

    
4. Plot the ROC curve and compute the AUC. What does this tell you?

5. You have measured the following values for a day in `SMA`
```{r,echo=TRUE,eval=FALSE}
testX <- tibble(sunshine=600, windGust=30, tempMean=21, precTot=10, humidMean=70)
```
Do you predict this to be a serene day?
    
    

## **2.** k-nearest neighbors


1. Fit `nearest_neighbor()` model with `kknn` engine on the same data as above. Use $k=5$. How is the accuracy of this model?

  _(Hint: remember to normalize the data!)_
  
2. Find the optimal parameter $k$ for the `nearest_neighbor()` model with the workflow set validation procedure as done in class. Use odd values of $k$ up to 53.
    1. use the function`vfold_cv` to build a 10 fold cross validation. Note that 
      * `vfold_cv` returns a list with element `splits` that contains all the data splits
      * you can access the training fold of a split with `analysis(vfold$split[[1]])`
      * you can access the validation fold of a split with `assessment(vfold$split[[1]])`
    
    2. familiarize yourself with the option `neighbors` of the model `nearest_neighbor()`. 
      * create a grid of neighbors to try for the model with the following code.  
      ```
      gridvals <- tibble(neighbors = seq(from = 1, to = 201, by = 2))
      ```
      * what is the difference between `gridvals` and the grid created in the lecture?
      
    3. use this grid to fit the workflow set
    
    4. Plot the cross validation results with autoplot. Which $k$ is optimal? 
    
    _(Hint: use `extract_workflow_set_result` to extract the workflow set results and `select_best` to find the optimal $k$)_
    
3. Compare the knn model with the optimal $k$ against the NB model in terms of ROC and AUC. Which model is better?

   1. Create a non-trained workflow for the knn model, use `finilize_workflow` to set the parameters of the non-trained workflow to the best parameters we found before. 
   2. Create a workflows set that contains both the knn and NB untrained workflows
   2. Train and evaluate on the validation set.
   3. Use `autoplot` to show the results for these two models
   4. For each workflow, you can simulate the pipeline of training on the full training set, testing on testing set with the function `last_fit`. Note: you first need to extract the individual workflow with `extract_workflow`. 



## **3.** Random forest


1. Fit a random forest model on the data. What are the most important features?

2. Compute the accuracy and the confusion matrix for this model. How does it compare to the knn and NB model? Which one would you choose if you wanted to minimize the false negatives?

3. Compare the 3 models proposed here with ROC and AUC. By looking at the ROC curve is there a model which is significantly better? What about the AUC, what does it tell you?

